# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rapgo_pb2 as rapgo__pb2


class RapGeneratorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFilename = channel.unary_unary(
        '/rapgo.RapGeneratorService/GetFilename',
        request_serializer=rapgo__pb2.GetFilenameRequest.SerializeToString,
        response_deserializer=rapgo__pb2.OutputFilename.FromString,
        )


class RapGeneratorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFilename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RapGeneratorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFilename': grpc.unary_unary_rpc_method_handler(
          servicer.GetFilename,
          request_deserializer=rapgo__pb2.GetFilenameRequest.FromString,
          response_serializer=rapgo__pb2.OutputFilename.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rapgo.RapGeneratorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
