# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rapgo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rapgo.proto',
  package='rapgo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0brapgo.proto\x12\x05rapgo\"&\n\x12GetFilenameRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"(\n\x0eOutputFilename\x12\x16\n\x0eoutputFilename\x18\x01 \x01(\t2X\n\x13RapGeneratorService\x12\x41\n\x0bGetFilename\x12\x19.rapgo.GetFilenameRequest\x1a\x15.rapgo.OutputFilename\"\x00\x62\x06proto3'
)




_GETFILENAMEREQUEST = _descriptor.Descriptor(
  name='GetFilenameRequest',
  full_name='rapgo.GetFilenameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='rapgo.GetFilenameRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)


_OUTPUTFILENAME = _descriptor.Descriptor(
  name='OutputFilename',
  full_name='rapgo.OutputFilename',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputFilename', full_name='rapgo.OutputFilename.outputFilename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['GetFilenameRequest'] = _GETFILENAMEREQUEST
DESCRIPTOR.message_types_by_name['OutputFilename'] = _OUTPUTFILENAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFilenameRequest = _reflection.GeneratedProtocolMessageType('GetFilenameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILENAMEREQUEST,
  '__module__' : 'rapgo_pb2'
  # @@protoc_insertion_point(class_scope:rapgo.GetFilenameRequest)
  })
_sym_db.RegisterMessage(GetFilenameRequest)

OutputFilename = _reflection.GeneratedProtocolMessageType('OutputFilename', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTFILENAME,
  '__module__' : 'rapgo_pb2'
  # @@protoc_insertion_point(class_scope:rapgo.OutputFilename)
  })
_sym_db.RegisterMessage(OutputFilename)



_RAPGENERATORSERVICE = _descriptor.ServiceDescriptor(
  name='RapGeneratorService',
  full_name='rapgo.RapGeneratorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=104,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFilename',
    full_name='rapgo.RapGeneratorService.GetFilename',
    index=0,
    containing_service=None,
    input_type=_GETFILENAMEREQUEST,
    output_type=_OUTPUTFILENAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAPGENERATORSERVICE)

DESCRIPTOR.services_by_name['RapGeneratorService'] = _RAPGENERATORSERVICE

# @@protoc_insertion_point(module_scope)
