apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapgeneratorservice
spec:
  selector:
    matchLabels:
      app: rapgeneratorservice
  template:
    metadata:
      labels:
        app: rapgeneratorservice
    spec:
      containers:
        - name: server
          image: rapgeneratorservice
          ports:
          - containerPort: 5000
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5000"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5000"]
          env:
          - name: PORT
            value: "5000"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/data/google-credentials/keen-dispatch.json"
          - name: SOUNDS_FOLDER
            value: "/data/sounds/"
          - name: GOOGLE_SOUND_BUCKET
            value: "rapgo-bucket-1"
          resources:
            requests:
              cpu: 700m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rapgeneratorservice
spec:
  type: ClusterIP
  selector:
    app: rapgeneratorservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 5000